DotNetCore/LogSpekt/LogSpekt/Controllers/LogSpektController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace LogSpekt.Controllers
{
    public class LogSpektController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ShowLogGroups()
        {
            return View();
        }
    }
}

DotNetCore/LogSpekt/LogSpekt/Views/LogSpekt/Index.cshtml
<div class="container">
    <div class="modal-body row">
        <div class="col-md-3">

            <form>
                <fieldset>
                    <legend>Search criteria</legend>
                    <div class="form-group">
                        <label class="control-label" for="focusedInput">Focused input</label>
                        <input class="form-control" id="focusedInput" type="text" value="This is focused..." style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHklEQVQ4EaVTO26DQBD1ohQWaS2lg9JybZ+AK7hNwx2oIoVf4UPQ0Lj1FdKktevIpel8AKNUkDcWMxpgSaIEaTVv3sx7uztiTdu2s/98DywOw3Dued4Who/M2aIx5lZV1aEsy0+qiwHELyi+Ytl0PQ69SxAxkWIA4RMRTdNsKE59juMcuZd6xIAFeZ6fGCdJ8kY4y7KAuTRNGd7jyEBXsdOPE3a0QGPsniOnnYMO67LgSQN9T41F2QGrQRRFCwyzoIF2qyBuKKbcOgPXdVeY9rMWgNsjf9ccYesJhk3f5dYT1HX9gR0LLQR30TnjkUEcx2uIuS4RnI+aj6sJR0AM8AaumPaM/rRehyWhXqbFAA9kh3/8/NvHxAYGAsZ/il8IalkCLBfNVAAAAABJRU5ErkJggg==&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;">
                    </div>

                    <div class="form-group">
                        <label for="select" class="control-label">Selects</label>
                        <select class="form-control" id="select">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="range-start" class="control-label">Range</label>

                        <div class="input-group input-daterange">
                            <input type="text" class="form-control" value="2012-04-05" id="range-start">
                            <div class="input-group-addon">to</div>
                            <input type="text" class="form-control" value="2012-04-19">
                        </div>
                    </div>

                </fieldset>
            </form>


            <div class="bs-component">
                <ul class="list-group">
                    <li class="list-group-item">
                        <span class="badge">14</span>
                        Number of bugs
                    </li>
                    <li class="list-group-item">
                        <span class="badge">2</span>
                        Number of warnings
                    </li>
                    <li class="list-group-item">
                        <span class="badge">1</span>
                        Number of infos
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9">
                    
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bs-component">
                            <table class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Column heading</th>
                                        <th>Column heading</th>
                                        <th>Column heading</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                    </tr>
                                    <tr class="info">
                                        <td>3</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                    </tr>
                                    <tr class="success">
                                        <td>4</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                    </tr>
                                    <tr class="danger">
                                        <td>5</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                    </tr>
                                    <tr class="warning">
                                        <td>6</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                    </tr>
                                    <tr class="active">
                                        <td>7</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                        <td>Column content</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div><!-- /example -->
                    </div>
                </div>

            <div class="text-center">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>

        </div>
    </div>
</div>

DotNetCore/LogSpekt/LogSpekt/Views/LogSpekt/ShowLogGroups.cshtml
<div class="container">
    <div class="modal-body row">
        <div class="col-md-3">

            <div class="row">
                <form>
                    <fieldset>
                        <legend>Search criteria</legend>

                        <div class="input-group">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">&lt;</button>
                            </span>
                            <input type="text" class="form-control" id="date" placeholder="Date">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">&gt;</button>
                            </span>
                        </div>

                    </fieldset>
                </form>
            </div>


            <div class="row top10">
                <div class="bs-component">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <span class="badge">14</span>
                            Number of bugs
                        </li>
                        <li class="list-group-item">
                            <span class="badge">2</span>
                            Number of warnings
                        </li>
                        <li class="list-group-item">
                            <span class="badge">1</span>
                            Number of infos
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-9">

            <div class="row">
                <div class="col-lg-12">
                    <div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3"> 
                        <h4>Cross-browser compatibility <span class="badge pull-right">4</span></h4>
                        <p>Progress bars use CSS3 transitions and animations to achieve some of their effects. These features are not supported in Internet Explorer 9 and below or older versions of Firefox. Opera 12 does not support animations.</p> 
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="bs-callout bs-callout-info" id="callout-alerts-no-default">
                        <h4>No default class <span class="badge pull-right">14</span></h4>
                        <p>Alerts don't have default classes, only base and modifier classes. A default gray alert doesn't make too much sense, so you're required to specify a type via contextual class. Choose from success, info, warning, or danger.</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="bs-callout bs-callout-warning" id="callout-navbar-btn-context">
                        <h4>Context-specific usage <span class="badge pull-right">334</span></h4>
                        <p>Like the standard <a href="../css/#buttons">button classes</a>, <code>.navbar-btn</code> can be used on <code>&lt;a&gt;</code> and <code>&lt;input&gt;</code> elements. However, neither <code>.navbar-btn</code> nor the standard button classes should be used on <code>&lt;a&gt;</code> elements within <code>.navbar-nav</code>.</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

DotNetCore/LogSpekt/LogSpekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    @*<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />*@
    <link href="~/css/test.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css" rel="stylesheet" />
    @*<link href="~/lib/bootswatch/simplex/bootstrap.css" rel="stylesheet" />*@
    <link href="~/css/custom.css" rel="stylesheet" />
    <link href="~/css/temp.css" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-controller="LogSpekt" asp-action="Index" class="navbar-brand">LogSpekt</a>
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-controller="LogSpekt" asp-action="Index">Logs</a>
                    </li>
                    <li>
                        <a asp-controller="LogSpekt" asp-action="ShowLogGroups">Log groups</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div>
        @RenderBody()
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/tether/dist/js/tether.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"></script>
    <script src="~/js/custom.js"></script>

</body>
</html>